@startuml
skinparam classAttributeIconSize 0
hide circle
skinparam backgroundColor transparent
skinparam shadowing false
skinparam dpi 150
skinparam classFontSize 15
skinparam classAttributeFontSize 14
skinparam ArrowColor #333333
skinparam classBorderColor #6a6a6a
skinparam classBackgroundColor #FFFFCC
title Controlador de Casos de Uso — un controlador por caso de uso
class "UI Cliente" as UC
class "Venta UI" as UV
class "UI Proveedor" as UP
class "ClientesCtrl" as CC #AED7F0
class "VentasCtrl" as VC #AED7F0
class "ComprasCtrl" as CoC #AED7F0
class ClassA
class ClassB
class ClassC
UC ..> CC
UV ..> VC
UP ..> CoC
CC --> ClassA
CC --> ClassB
VC --> ClassB
CoC --> ClassB
CoC --> ClassC
@enduml
