@startuml
skinparam classAttributeIconSize 0
hide circle
skinparam backgroundColor transparent
skinparam shadowing false
skinparam dpi 150
skinparam classFontSize 15
skinparam classAttributeFontSize 14
skinparam ArrowColor #333333
skinparam classBorderColor #6a6a6a
skinparam class {
  BackgroundColor #FFFFCC
  BackgroundColor<<control>> #AED7F0
  BackgroundColor<<ui>> #FFFFCC
}
title Creador — La Factura crea sus LineaFactura
class Factura
class LineaFactura
Factura "1" *-- "1..*" LineaFactura : crea / contiene >
@enduml
